@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 公司管理员
participant Login
participant RoleRight
participant DB

公司管理员->Login :登录()
activate 公司管理员
activate Login
Login->RoleRight  : 修改普通用户权限()
activate RoleRight
RoleRight->DB :改变数据库()
activate DB
RoleRight<-DB :返回页面结果信息()
activate RoleRight
deactivate
deactivate
deactivate
deactivate
deactivate 公司管理员
@enduml